    boost::mpl::v_item<
        boost::mpl::map1<boost::mpl::pair<
            mpllibs::metaparse::v2::string<'o',
                                           'b',
                                           'j',
                                           'e',
                                           'c',
                                           't',
                                           ' ',
                                           'w',
                                           'i',
                                           't',
                                           'h',
                                           ' ',
                                           'a',
                                           'r',
                                           'r',
                                           'a',
                                           'y',
                                           ' ',
                                           'o',
                                           'f',
                                           ' ',
                                           's',
                                           'o',
                                           'm',
                                           'e',
                                           ' ',
                                           't',
                                           'y',
                                           'p',
                                           'e',
                                           's'>,
            boost::mpl::v_item<
                boost::mpl::map0<mpl_::na>,
                boost::mpl::v_item<
                    boost::mpl::vector0<mpl_::na>,
                    boost::mpl::v_item<
                        genrile::metaparse::Null,
                        boost::mpl::v_item<
                            std::__1::integral_constant<bool, false>,
                            boost::mpl::vector1<
                                std::__1::integral_constant<bool, true> >,
                            0>,
                        0>,
                    0>,
                0> > >,
        boost::mpl::v_item<
            boost::mpl::map1<boost::mpl::pair<
                mpllibs::metaparse::v2::
                    string<'a', ' ', 'd', 'o', 'u', 'b', 'l', 'e'>,
                genrile::metaparse::boxed_real_string<
                    mpllibs::metaparse::v2::
                        string<'1', '.', '2', '3', '4', 'e', '4', '5'> > > >,
            boost::mpl::v_item<
                mpllibs::metaparse::v2::string<'r', 'o', 's', 'e', 'b', 'u', 'd'>,
                boost::mpl::vector1<mpllibs::metaparse::v2::string<'J',
                                                                   'S',
                                                                   'O',
                                                                   'N',
                                                                   ' ',
                                                                   'T',
                                                                   'e',
                                                                   's',
                                                                   't',
                                                                   ' ',
                                                                   'P',
                                                                   'a',
                                                                   't',
                                                                   't',
                                                                   'e',
                                                                   'r',
                                                                   'n',
                                                                   ' ',
                                                                   'p',
                                                                   'a',
                                                                   's',
                                                                   's',
                                                                   '1'> >,
                0>,
            0>,
        0>
